# Generated by Django 3.2.25 on 2026-02-24 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfers', '0005_alter_transfer_status'),
        ('dashboard_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('operator', models.CharField(max_length=40)),
                ('amount', models.PositiveIntegerField()),
                ('disburse_token', models.CharField(blank=True, max_length=100)),
                ('disburse_ref_id', models.CharField(blank=True, max_length=60)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('provider_ref', models.CharField(blank=True, max_length=100)),
                ('paydunya_status', models.CharField(blank=True, max_length=20)),
                ('paydunya_desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_disbursements', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_disbursements', to='transfers.transfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
