# Generated by Django 3.2.25 on 2026-02-25 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_admin', '0002_manualdisbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_create', 'Créer utilisateur'), ('user_edit', 'Modifier utilisateur'), ('transfer_edit', 'Modifier transfert'), ('transfer_delete', 'Supprimer transfert'), ('transfer_retry', 'Relancer transfert'), ('credit_retry', 'Relancer crédit'), ('credit_retry_all', 'Relancer tous crédits'), ('reconcile', 'Réconciliation disbursing'), ('fee_edit', 'Modifier frais opérateur'), ('support_reply', 'Répondre ticket support'), ('support_resolve', 'Résoudre ticket support'), ('manual_disburse', 'Déboursement manuel'), ('disburse_check', 'Vérifier déboursement')], max_length=30)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
