# Generated by Django 3.2.25 on 2025-11-17 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_wallet', models.CharField(max_length=20)),
                ('to_wallet', models.CharField(max_length=20)),
                ('from_phone', models.CharField(max_length=15)),
                ('to_phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('our_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('paydunya_invoice_token', models.CharField(blank=True, max_length=100)),
                ('paydunya_payment_ref', models.CharField(blank=True, max_length=100)),
                ('disburse_token', models.CharField(blank=True, max_length=100)),
                ('disburse_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('created', 'Créé'), ('invoice_sent', 'Facture envoyée'), ('otp_waiting', 'En attente OTP'), ('debited', 'Débité'), ('disbursing', 'En cours de crédit'), ('success', 'Réussi'), ('failed', 'Échoué')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
