# Generated by Django 3.2.25 on 2025-11-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20, unique=True)),
                ('payin_fee_percent', models.DecimalField(decimal_places=3, max_digits=5)),
                ('payout_fee_percent', models.DecimalField(decimal_places=3, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
