# Generated by Django 3.2.25 on 2025-11-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_operatorfees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='our_fee',
        ),
        migrations.AddField(
            model_name='transfer',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transfer',
            name='amount_sent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transfer',
            name='estimated_net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transfer',
            name='our_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transfer',
            name='our_fee_percent',
            field=models.DecimalField(decimal_places=3, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transfer',
            name='payin_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transfer',
            name='payin_fee_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transfer',
            name='payout_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transfer',
            name='payout_fee_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transfer',
            name='total_debited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='operatorfees',
            name='payin_fee_percent',
            field=models.DecimalField(decimal_places=3, default=2.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='operatorfees',
            name='payout_fee_percent',
            field=models.DecimalField(decimal_places=3, default=2.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('created', 'Créé'), ('invoice_sent', 'Facture envoyée'), ('debited', 'Débité'), ('disbursing', 'En cours de crédit'), ('success', 'Réussi'), ('failed', 'Échoué')], default='created', max_length=20),
        ),
    ]
