# Generated by Django 3.2.25 on 2025-12-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_auto_20251118_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorfees',
            name='our_fee_percent',
            field=models.DecimalField(decimal_places=3, default=1.5, help_text='Ta commission sur chaque transfert (ex: 1.5%)', max_digits=5),
        ),
    ]
