# Generated by Django 3.2.25 on 2026-02-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_operatorfees_our_fee_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('created', 'Créé'), ('invoice_sent', 'Facture envoyée'), ('debited', 'Débité'), ('pending_wave', 'En attente Wave'), ('pending_mtn', 'En attente MTN'), ('disbursing', 'En cours de crédit'), ('success', 'Réussi'), ('failed', 'Paiement refusé'), ('credit_failed', 'Débité – Crédit échoué')], default='created', max_length=20),
        ),
    ]
