"""
Django settings for money_transfer project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# URL de base dynamique (automatique selon l'environnement)
BASE_URL = os.getenv('RENDER_EXTERNAL_URL') or os.getenv('BASE_URL', 'http://127.0.0.1:8000')

# Webhook PayDunya (ngrok ou Render)
PAYDUNYA_WEBHOOK_URL = f"{BASE_URL.rstrip('/')}/api/transfer/webhook-paydunya/"

# Optionnel : pour les logs
print(f"WEBHOOK URL → {PAYDUNYA_WEBHOOK_URL}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b2mx7nu+0na6sojvt#mdh=8^&6=t232+t8-uj0d#+j@mj_lg53'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    # AJOUTE TON URL NGROK ICI
    'buudi-inter-backend.onrender.com'
]





INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'users',
    'transfers',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'money_transfer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'money_transfer.wsgi.application'


# CORS (pour ton app Flutter)
CORS_ALLOW_ALL_ORIGINS = True  # Prod: liste blanche

# PayDunya

PAYDUNYA = {
    'MASTER_KEY': 'uCte9yl8-XmNY-A9bD-XpUf-359KxPQYsjSu',
    'PRIVATE_KEY': 'live_private_3iYqXPwvkhCFoJD0sY9WnueKe27',
    'TOKEN': 'B0BRPJaRk2fujyHiguvX',
    'BASE_URL': 'https://app.paydunya.com',
}




# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# settings.py ou dans un modèle
WALLET_CONFIG = {
    "orange": {
        "name": "Orange Money",
        "ussd": "#144*82# (option 2)",
        "needs_otp": True,
        "has_popup": False,
        "softpay_endpoint": "orange-money-ci"
    },
    "mtn": {
        "name": "MTN MoMo",
        "ussd": None,
        "needs_otp": False,
        "has_popup": False,
        "softpay_endpoint": "mtn-ci"
    },
    "moov": {
        "name": "Moov Money",
        "ussd": None,
        "needs_otp": False,
        "has_popup": True,
        "softpay_endpoint": "moov-ci"
    },
    "wave": {
        "name": "Wave",
        "ussd": None,
        "needs_otp": False,
        "has_popup": True,
        "softpay_endpoint": "wave-ci"
    }
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATIC_URL = '/static/'

# AJOUT OBLIGATOIRE pour collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'